spring.application.name=DATN
spring.jackson.date-format=dd/MM/yyyy
spring.datasource.url=jdbc:mysql://localhost:3306/your_database
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=1234
<<<<<<< HEAD


=======
>>>>>>> 2737feb9f6b602c7b2f4ffe0782eb9372e6c60e0
# C?u hÃ¬nh JPA
=======
spring.datasource.password=12345678
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# C?u h?nh JPA
>>>>>>> deac4cb8498948e08132fb1b64201d994b80e6e0
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
# ?? xem các câu l?nh SQL

# ?? xem log chi ti?t h?n
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicTypeDescriptor=TRACE

# environment variable
api.prefix=/api/v1

#secret_key and duration
huudung.secret.key=bmd1b2l0aGVvaHVvbmdob2FtYXltdWdpYW5nbG9pbGFuc3VvbmdraG9pcGhvaXBoYWR1d2FidW9jYWl4YXJvaQ==
huudung.duration.date=86400
logging.level.org.springframework.security=DEBUG